version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27017:27017"