version: '3'
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: animalquiz
    ports:
      - "27017:27017"
  server:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db